### ISSUE TITLE
Error when trying unit junit tests

### ISSUE THREAD

**Issue by Silthus** [EntryPointKR/Spigradle#6]
First off, thanks for the great resource!

However if I try to run tests using [MockBukkit](https://github.com/seeseemelk/MockBukkit) I get the error that no `plugin.yml` can be found.

Is there a way to create a tasks that generates the `plugin.yml` so it can be used by unit tests?

Thanks!

**Comment by EntryPointKR** [comment]
Hi! Thanks for sharing your experience.

If you tried MockBukkit.load() for loading a plugin, then it will cause the error because Spigradle doesn't generate plugin.yml into resources folder like `src/main/java/resources/plugin.yml`.
But it will be stored in `build/tmp/spigotPluginYaml/plugin.yml`. 

Accroding to above information, we can try these option:
1. Use loadWith(Class, File) 
`MockBukkit.loadWith(Main.class, new File("build/tmp/spigotPluginYaml/plugin.yml"));`

2. Use Gradle copy task

```
task copyPluginYaml(type: Copy, dependsOn: spigotPluginYaml) {
    from(new File(spigotPluginYaml.temporaryDir, "plugin.yml"))
    into(sourceSets.main.resources.srcDirs[0])
}

tasks.test.dependsOn(copyPluginYaml)
```

Then before executing test task, it will copy the plugin.yml into project resources folder. but it seems will fail at first execution.

**Comment by Silthus** [comment]
Thanks! I used the second option and it worked :)

**Comment by Silthus** [comment]
//UPDATE:

I switched to your recommended, first method. Having a plugin.yml in the resources folder creates a duplicate plugin.yml inside the final .jar

**Comment by EntryPointKR** [comment]
Oh right. if you want to do second option, change 'main' to 'test'

```
task copyPluginYaml(type: Copy, dependsOn: spigotPluginYaml) {
    from(new File(spigotPluginYaml.temporaryDir, "plugin.yml"))
    into(sourceSets.test.resources.srcDirs[0]) // <-- Changed to sourceSets.test from sourceSets.main
}

tasks.test.dependsOn(copyPluginYaml)
```

Then, it will not contains duplicate plugin.yml, also it will not fail at first execution.
